# docker-compose.yml
version: '3'

services:
  generator:
    build: ./generator
    environment:
      KAFKA_BROKER_URL: 'kafka:9092'
      TOPIC_OUTPUT: 'ProductClusters'
      TIMEOUT_POLLING_MS: 10
      MAX_RECORD_POLLING: 5
      MESSAGES_PER_SECOND: 1000
      MONGODB_ADDRESS: "mongodb:27017"
      DATABASE: 'LabeledDomainClusters'
    external_links:
      - mongo

  detector:
    build: detector
    container_name: 'detector'
    environment:
      KAFKA_BROKER_URL: 'kafka:9092'
      TOPIC_INPUT: 'ProductClusters'
      TOPIC_OUTPUT: 'ClassifiedProducts'
      TIMEOUT_POLLING_MS: 10
      MAX_RECORD_POLLING: 5
      MESSAGES_PER_SECOND: 1000
      TRAINING_SET: '/data/training_set.csv'
      TRAINING_PARQUET: '/data/training_set.snappy.parquet'
      MODEL: '/model/classifier_page.sav'
      MONGODB_ADDRESS: "mongodb:27017"
      DATABASE_WRITE: 'ClassifiedProducts'
      DATABASE_READ: 'CrawledPages'
    external_links:
      - mongo
    volumes:
      - ./detector/src:/src
      - ./detector/data:/data
      - ./detector/model:/model


# Give this composition access to the Kafka network
networks:
  default:
    external:
      name: environment-network